name: Build Executable

on:
  workflow_dispatch:  # Allows for manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-local.txt --target .
          pip install cx_Freeze

      - name: Build the executable
        run: |
          python setup.py build

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: AstroDwarfScheduler
          path: build\exe.win-amd64-3.12\  # Adjust this path based on your Python version and cx_Freeze setup
